version: '3.4'

networks:
  monitoring:
    external: true

# logging section
#x-logging: 
  #&loki-logging
  #driver: loki
  #options:
    #loki-url: http://host.docker.internal:3100/loki/api/v1/push

services:
  gateway:
    build: ./docker
    image: kjtully/spring-cloud-gateway:latest
    container_name: gateway
    labels:
      desciption: "Spring Cloud Gateway"
    environment:
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "$APPDYNAMICS_AGENT_APPLICATION_NAME"
      APPDYNAMICS_AGENT_TIER_NAME: "Spring-Cloud-Gateway"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "gateway"
      NEW_RELIC_APP_NAME: "$NEW_RELIC_APP_NAME"
      NEW_RELIC_LICENSE_KEY: "$NEW_RELIC_LICENSE_KEY"
      #JAVA_OPTS: ""
      JAVA_OPTS: "-javaagent:/opt/appdynamics/java/javaagent.jar"
      #JAVA_OPTS: "-javaagent:/opt/newrelic/java/newrelic/newrelic.jar"
      # MacOS - uncomment the NETVIZ env vars to use local docker-compose network
      #APPDYNAMICS_NETVIZ_AGENT_HOST: "$APPDYNAMICS_NETVIZ_AGENT_HOST"
      #APPDYNAMICS_NETVIZ_AGENT_PORT: "$APPDYNAMICS_NETVIZ_AGENT_PORT"
      #APPDYNAMICS_BROWSER_EUM_APPKEY: "$APPDYNAMICS_BROWSER_EUM_APPKEY"
      #APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP"
      #APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS"
      #APPDYNAMICS_BROWSER_EUM_BEACON_HTTP: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTP"
      #APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS"
      # Docker Hostname to pre-populate Jaeger link in UI
      #DOCKER_HOSTNAME: "$DOCKER_HOSTNAME"
    ports:
      - "9999:9999"
      - "9010:9010"
    networks:
      - monitoring
    #logging: *loki-logging
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2'
          #NanoCpus: '750000000'
          memory: 512M
        reservations:
          cpus: '1'
          #NanoCPUs: '250000000'
          memory: 256M

